/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import BUS.PhanQuyenBUS;
import javax.swing.*;

/**
 *
 * @author PC
 */
public class DlgThemQuyen extends javax.swing.JDialog {

    PhanQuyenBUS pqBUS = new PhanQuyenBUS();
    public DlgThemQuyen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    DlgThemQuyen() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkBanHang = new javax.swing.JCheckBox();
        chkSanPham = new javax.swing.JCheckBox();
        chkKhachHang = new javax.swing.JCheckBox();
        chkNhanVien = new javax.swing.JCheckBox();
        chkNhapHang = new javax.swing.JCheckBox();
        chkKhuyenMai = new javax.swing.JCheckBox();
        chkPhanQuyen = new javax.swing.JCheckBox();
        chkThongKe = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtQuyen = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        chkBanHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkBanHang.setText("Quản lý bán hàng");
        chkBanHang.setMargin(new java.awt.Insets(8, 8, 8, 8));
        chkBanHang.setRolloverEnabled(false);

        chkSanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkSanPham.setText("Quản lý sản phẩm");
        chkSanPham.setMargin(new java.awt.Insets(8, 8, 8, 8));

        chkKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkKhachHang.setText("Quản lý khách hàng");
        chkKhachHang.setMargin(new java.awt.Insets(8, 8, 8, 8));
        chkKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKhachHangActionPerformed(evt);
            }
        });

        chkNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkNhanVien.setText("Quản lý nhân viên");
        chkNhanVien.setMargin(new java.awt.Insets(8, 8, 8, 8));

        chkNhapHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkNhapHang.setText("Quản lý nhập hàng");
        chkNhapHang.setMargin(new java.awt.Insets(8, 8, 8, 8));

        chkKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkKhuyenMai.setText("Quản lý khuyến mãi");
        chkKhuyenMai.setMargin(new java.awt.Insets(8, 8, 8, 8));
        chkKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKhuyenMaiActionPerformed(evt);
            }
        });

        chkPhanQuyen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkPhanQuyen.setText("Quản lý phân quyền");
        chkPhanQuyen.setMargin(new java.awt.Insets(8, 8, 8, 8));
        chkPhanQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPhanQuyenActionPerformed(evt);
            }
        });

        chkThongKe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkThongKe.setText("Quản lý thống kê");
        chkThongKe.setMargin(new java.awt.Insets(8, 8, 8, 8));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên quyền mới");

        txtQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuyenActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(0, 153, 153));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkBanHang)
                                    .addComponent(chkSanPham)
                                    .addComponent(chkKhachHang)
                                    .addComponent(chkNhanVien)
                                    .addComponent(chkNhapHang)
                                    .addComponent(chkKhuyenMai)
                                    .addComponent(chkPhanQuyen)
                                    .addComponent(chkThongKe)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(chkBanHang)
                .addGap(0, 0, 0)
                .addComponent(chkSanPham)
                .addGap(0, 0, 0)
                .addComponent(chkKhachHang)
                .addGap(0, 0, 0)
                .addComponent(chkNhanVien)
                .addGap(0, 0, 0)
                .addComponent(chkNhapHang)
                .addGap(0, 0, 0)
                .addComponent(chkKhuyenMai)
                .addGap(0, 0, 0)
                .addComponent(chkPhanQuyen)
                .addGap(0, 0, 0)
                .addComponent(chkThongKe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkKhachHangActionPerformed

    private void chkKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKhuyenMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkKhuyenMaiActionPerformed

    private void chkPhanQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPhanQuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPhanQuyenActionPerformed

    private void txtQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuyenActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        // 1. Lấy và kiểm tra tên quyền
        String Quyen = txtQuyen.getText();
        if (Quyen == null || Quyen.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên quyền mới!");
            return;
        }

        // 2. Lấy các giá trị quyền từ Checkbox
        // Tạo đối tượng DTO.PhanQuyen
    DTO.PhanQuyen pq = new DTO.PhanQuyen();
    pq.setQuyen(Quyen);
    pq.setQLBanHang(chkBanHang.isSelected());
    pq.setQLNhapHang(chkNhapHang.isSelected());
    pq.setQLNhanVien(chkNhanVien.isSelected());
    pq.setQLSanPham(chkSanPham.isSelected());
    pq.setQLKhachHang(chkKhachHang.isSelected());
    pq.setQLKhuyenMai(chkKhuyenMai.isSelected());
    pq.setQLPhanQuyen(chkPhanQuyen.isSelected());
    pq.setQLThongKe(chkThongKe.isSelected());

    // Gọi BUS để thực hiện INSERT
    boolean kq = pqBUS.insertQuyen(pq);

        // 4. Xử lý kết quả
        if (kq) {
            JOptionPane.showMessageDialog(this, "Thêm quyền [" + Quyen + "] thành công!");
            this.dispose(); // Đóng Dialog sau khi thành công
        } else {
            JOptionPane.showMessageDialog(this, "Thêm quyền thất bại! (Lỗi: Tên quyền có thể đã tồn tại)");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgThemQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgThemQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgThemQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgThemQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgThemQuyen dialog = new DlgThemQuyen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JCheckBox chkBanHang;
    private javax.swing.JCheckBox chkKhachHang;
    private javax.swing.JCheckBox chkKhuyenMai;
    private javax.swing.JCheckBox chkNhanVien;
    private javax.swing.JCheckBox chkNhapHang;
    private javax.swing.JCheckBox chkPhanQuyen;
    private javax.swing.JCheckBox chkSanPham;
    private javax.swing.JCheckBox chkThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtQuyen;
    // End of variables declaration//GEN-END:variables
}
